-- ─────────────────────────────────────────────────────────────────────────────
-- Zasterix-V5 — Supabase "Brain" Schema
--
-- Apply this file once against your Supabase project:
--   Dashboard → SQL Editor → paste and run, OR
--   supabase db push  (if using the Supabase CLI)
--
-- Tables:
--   agent_tasks  — source of truth for all agent work (Pillar 2)
--   registry     — dynamically generated code strings saved by agents (Pillar 3)
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable the pgcrypto extension so gen_random_uuid() is available
create extension if not exists "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- agent_tasks
-- Every row represents one unit of work for the Engine to process.
-- The Engine polls this table, claims rows atomically, and checkpoints
-- current_step + updated_at before every step transition.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists agent_tasks (
  id            uuid        primary key default gen_random_uuid(),
  type          text        not null,
  status        text        not null default 'pending'
                            check (status in ('pending', 'active', 'completed', 'failed')),
  current_step  text,
  input         jsonb,
  output        jsonb,
  -- reasoning field: every task must document why it serves Independence & Humanity
  -- (see CONSTITUTION.md Article II)
  reasoning     text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Index for the polling query: status IN ('pending', 'active') ORDER BY created_at
create index if not exists idx_agent_tasks_status_created
  on agent_tasks (status, created_at asc);

-- Index for stale-task recovery: active tasks older than the staleness threshold
create index if not exists idx_agent_tasks_active_updated
  on agent_tasks (status, updated_at asc)
  where status = 'active';

-- ─────────────────────────────────────────────────────────────────────────────
-- registry
-- Stores JavaScript code strings generated by agents.
-- The Engine loads rows from here and executes them in a vm2 sandbox with a
-- pre-injected Supabase client (Pillar 3).
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists registry (
  id          uuid        primary key default gen_random_uuid(),
  name        text        not null unique,
  code        text        not null,
  -- reasoning field is MANDATORY — no reasoning = change must not proceed
  -- (see CONSTITUTION.md Article II)
  reasoning   text        not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Index for name-based lookup when the Engine loads a code module by name
create index if not exists idx_registry_name on registry (name);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- The Engine uses the Service Role Key (bypasses RLS).
-- The Dashboard uses the Anon Key — restrict to read-only on agent_tasks and
-- no access to registry (code strings must never be exposed to the browser).
-- ─────────────────────────────────────────────────────────────────────────────
alter table agent_tasks enable row level security;
alter table registry    enable row level security;

-- Dashboard (anon/authenticated users): can insert new tasks and read their own
create policy "anon can insert agent_tasks"
  on agent_tasks for insert
  to anon
  with check (true);

create policy "anon can read agent_tasks"
  on agent_tasks for select
  to anon
  using (true);

-- registry is engine-only — no anon access
-- (The Service Role Key bypasses RLS entirely, so the engine always has access.)

-- ─────────────────────────────────────────────────────────────────────────────
-- Trigger: keep updated_at current on every row update
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace trigger trg_agent_tasks_updated_at
  before update on agent_tasks
  for each row execute function set_updated_at();

create or replace trigger trg_registry_updated_at
  before update on registry
  for each row execute function set_updated_at();
